name: auth
description: Authentication Handler package. This package will be responsible
  for authentication within our application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  build_runner: ^2.1.7
  flutter:
    sdk: flutter
  google_sign_in: ^5.2.3
  http: ^0.13.4
  integration_test: ^0.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17
  very_good_analysis: ^2.4.0
